
WINDOW_LOCATION_X = 500
WINDOW_LOCATION_Y = 200

WINDOW_HEIGHT = 600
WINDOW_WIDTH  = 1200

MENU_BUTTON_NUM = 4
MENU_BUTTON_HEIGHT = 100
MENU_BUTTON_WIDTH = WINDOW_WIDTH // MENU_BUTTON_NUM

CODE_TO_DISPLAY_TABLE = {
    'main': '主頁面',
    'customer': '顧客資料',
    'schedule': '預約畫面',
    'order': '歷史紀錄'
    
}